# Авторство и разработка плагина принадлежит разработчику с игровым никнеймом NaulbiMIX.
# Контактная информация разработчика:
# ВКонтакте - https://vk.com/evildonat https://vk.com/evil_donat https://vk.com/naulbirtl
# Telegram - https://t.me/naulbimix
# Создано при поддержке FlatiCommunity (https://t.me/flaticommunity)
#
# Плагин защищён авторским правом!
# Любые копирования, изменения, дополнения категорически запрещаются законом УК РФ Глава 70 Статья 1255. Авторское право.
# При возникновении выше перечисленных ситуаций или просьбам разрешения автора Вам использовать авторство разработки обращайтесь по контактной информации разработчика.
#
# Команды плагина:
# /booster /nlbbooster - Установить значение буста на сервере;
# /online /nlbonline /fakeonline /list - Узнать настоящий и фейковый онлайн на сервере.
#
# Настройки сообщений
messages:
  # Вы безправный
  noPermission: '&cУ вас недостаточно прав!'
  # Использование команды
  usage: '&fИспользование: /booster [Значение]'
  # Новое значение для буста
  newValue: '&fУстановлено значение: $value' # $value - Значение
  # Информация об онлайне
  online: '&6&l[*] &fИгроков на проекте: $onlineBoost &7(Реальный: $online, Буст: x$boost)' # $online - Онлайн без буста, $onlineBoost - онлайн с бустом, $boost - буст
  # Ошибка при получение числа из значения. Округляется до целых!
  noBoostValue: '&fУстанавливаемое значение не является числом.'
# Настройки
settings:
  # Права
  permission:
    # Права на использование буста
    booster: 'nlbbooster.booster'
    # Права на команду онлайна
    online: 'nlbbooster.online'
  # Буст по умолчанию. Данное значение будет меняться если будете через команду менять.
  boost: 1.5