# Авторство и разработка плагина принадлежит разработчику с игровым никнеймом NaulbiMIX.
# Контактная информация разработчика:
# ВКонтакте - https://vk.com/evildonat https://vk.com/evil_donat https://vk.com/naulbirtl
# Telegram - https://t.me/naulbimix
# Создано при поддержке FlatiCommunity (https://t.me/flaticommunity)
#
# Плагин защищён авторским правом!
# Любые копирования, изменения, дополнения категорически запрещаются законом УК РФ Глава 70 Статья 1255. Авторское право.
# При возникновении выше перечисленных ситуаций или просьбам разрешения автора Вам использовать авторство разработки обращайтесь по контактной информации разработчика.
#
# Название плагина
name: nlbBooster
# Версия плагина
version: 1.2
# Главный класс плагина
main: ru.naulbimix.nlbBooster.Main
# Автор плагина
author: NaulbiMIX
# Описание плагина
description: 'Буст онлайна как на автодобе'